sales/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views
from .views.add_bundle_view import add_bundle_page_view
from .views.add_transaction_view import create_transaction
from .views.transaction_list import TransactionList
from .views.add_order_view import create_order
from .views.add_payment_view import create_payment
from .views.bundle_list_view import bundle_list
from .views.bundle_product_list_view import bundle_products_list
from .views.add_client import create_client
from .views.client_sales import client_sales
from .views.client_list import ClientList
from .views.order_list import OrderList
from .views.invoice_view import invoice_page_view
from .views.transaction_details import transaction_detail_view
from .views.client_sales_list import ClientSalesList
from .views.client_sales_details import client_sales_detail_view



router = routers.DefaultRouter()

router.register('bundle', views.BundleView)
router.register('bundleProduct', views.BundleProductView)
router.register('order', views.OrderView)
router.register('orderProduct', views.OrderProductView)
router.register('transaction', views.TransactionView)
router.register('clients', views.ClientsView)
router.register('clientSales', views.ClientSalesView)




urlpatterns = [
    path('create-bundles/', add_bundle_page_view, name='add_bundle'),
    path('bundles/', bundle_list, name='bundle_list'),

    path('bundles/<int:id>', bundle_products_list, name='bundle_product_list'),

    path('create-order/', create_order, name='add_order'),
    path('all-order/', OrderList.as_view(), name='all_order'),

    path('create-transaction/', create_transaction, name='add_transaction'),
    path('all-transaction/', TransactionList.as_view(), name='all_transaction'),
    path('transaction/<int:id>', transaction_detail_view, name='transaction_detail'),

    path('create-payment/', create_payment, name='add_payment'),

    path('create-client/', create_client, name='add_client'),
    path('create-client-sales/', client_sales, name='client-sales'),
    path('all-client-sales/', ClientSalesList.as_view(), name='client_sales_list'),
    path('client-sales/<int:id>', client_sales_detail_view, name='client_sales_detail'),
    path('clients/', ClientList.as_view(), name='client_list'),

    path('invoice/', invoice_page_view, name='invoice'),

    # API URLs
    path('api/sales/', include(router.urls)),

]

users/urls.py
from django.urls import path,include
from users.views.login import login_view
from users.views.dashboard import dashboard_view
from users.views.create import create_user_view, store_user
from users.views.user_list import user_list_view
from users.views.csv_import import user_csv_import
from users.views.logout import logout_view
from users.views.user_detail import user_detail_view
from users.views.change_user_details import update_user
# from users.views.reset_password_email_view import reset_password_page
# from users.views.reset_password_done import reset_password_done

from django.conf import settings
from django.conf.urls.static import static



app_name = 'users'

urlpatterns = [
                  path('login/', login_view, name='login'),
                  path('dashboard/',dashboard_view,name='dashboard'),
                  path('create-user/',create_user_view, name='create_user_view'),
                  path('store-user/', store_user, name='store_user'),
                  path('update-user/', update_user, name='update_user'),

                  path('users/', user_list_view, name='user-list'),
                  path('users/<int:id>/', user_detail_view, name='user-detail'),

                  path('user-csv-import/', user_csv_import, name='user_csv_import'),
                  path('logout/', logout_view, name='logout'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models/permission_model.py
from django.db import models

class Permissions(models.Model):
	#id 	   =
	#module    =
	role_id    = models.IntegerField(max_length=5, blank=False, null=False)
	create 	   = models.BooleanField(default=True, null=False)
	read 	   = models.BooleanField(default=True, null=False)
	update 	   = models.BooleanField(default=True, null=False)
	delete 	   = models.BooleanField(default=True, null=False)
	created_at = models.DateTimeField(auto_now=True)
	updated_at = models.DateTimeField(auto_now=True)

users/models/session.py
from django.db import models

class Session(models.Model):
    session_key_id = models.IntegerField(auto_created=True, primary_key=True, unique=True)
    session_ey     = models.CharField(max_length=40, null=False, unique=True)
    session_data   = models.CharField(max_length=40, null=False)
    expiry_date    = models.DateTimeField()

users/models/user_model.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.contrib.auth.models import (
        BaseUserManager,
        AbstractBaseUser
    )

#Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.is_active = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user( email, password=password)
        user.is_admin=True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(unique=True, verbose_name='email address')
    name = models.CharField(max_length=40)
    phone = models.CharField(max_length=20, blank=False)
    avatar = models.ImageField(upload_to='images', blank=True)
    status = models.CharField(max_length=15, null=False)
    designation = models.CharField(max_length=40, null=False, default='Designation not set')

    created_by = models.CharField(max_length=40, blank=True)
    updated_by = models.CharField(max_length=40, blank=True)

    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_viewer = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, module):
        return True

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return reverse("users:user-detail", kwargs={"id": self.id})

        #return "/users/%i/" % self.id

users/views/change_user_details.py
from django.shortcuts import render, redirect, get_object_or_404
from users.models.user_model import User
from django.contrib.auth.decorators import login_required
import os
from django.conf import settings
from django.core.files.storage import default_storage


@login_required(login_url='/login/')
def update_user(request):
    """
        This view changes user details and updates them
    """

    if request.user.is_admin:

        user_obj = get_object_or_404(User, id=request.POST.get("user_id"))
        print(user_obj)

        name = request.POST.get("name")
        password = request.POST.get("password")
        phone = request.POST.get("phone")
        designation = request.POST.get("designation")
        isActive = request.POST.get("user_status")
        role = request.POST.get("role_id")
       # avatar = request.POST.get("avatar")
        if 'avatar' in request.FILES:
             user_obj.avatar.delete(False)#this line deletes the previous saved pro pic
             avatar_file = request.FILES["avatar"]
             save_path = os.path.join(settings.MEDIA_ROOT, avatar_file.name)
             default_storage.save(save_path, avatar_file)
             user_obj.avatar = avatar_file.name

        user_obj.name = name
        # user_obj.email = email
        user_obj.set_password(password)
        user_obj.phone = phone
        user_obj.designation = designation
        user_obj.status = isActive
        if isActive == 'Active':
            user_obj.is_active = True
        else:
            user_obj.is_active = False

        if role == "s":
            user_obj.is_staff = True
        elif role == "a":
            user_obj.is_admin = True
        elif role == "v":
            user_obj.is_viewer = True

        # save_path = os.path.join(settings.MEDIA_ROOT, avatar_file.name)
        # default_storage.save(save_path, avatar_file)
        #
        # user_obj.avatar = avatar_file.name
        user_obj.save()

        return redirect("/users/" + str(request.POST.get('user_id')))
    else:
        return render(request, "user_detail.html")

users/views/create.py
from django.shortcuts import render, redirect
from users.models import User
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
import os
from django.conf import settings
from django.core.files.storage import default_storage


@login_required(login_url='/login/')
def create_user_view(request):
    """
    This view Renders Create User Page
    """
    if request.user.is_admin:
        context = {
            "title": "Create User"
        }
        return render(request, 'create_user.html', context)
    else:
        return redirect('/dashboard/')


@login_required(login_url='/login/')
def store_user(request):
    """
    This view creates user and Store user in DB
    """
    if request.user.is_admin:
        formData = User()
        name = request.POST.get("name")
        email = request.POST.get("email")
        password = request.POST.get("password")
        phone = request.POST.get("phone")
        designation = request.POST.get("designation")
        isActive = request.POST.get("user_status")
        role = request.POST.get("role_id")
        if 'avatar' in request.FILES:
             avatar_file = request.FILES["avatar"]
             save_path = os.path.join(settings.MEDIA_ROOT, avatar_file.name)
             default_storage.save(save_path, avatar_file)
             formData.avatar = avatar_file.name

        formData.name = name
        formData.email = email
        formData.password = make_password(password)
        formData.phone = phone
        formData.designation = designation
        formData.status = isActive

        if isActive == 'Active':
            formData.is_active = True
        else :
            formData.is_active = False

        if role == "s":
            formData.is_staff = True
        elif role == "a" :
            formData.is_admin = True
        elif role == "v" :
            formData.is_viewer = True

        # save_path = os.path.join(settings.MEDIA_ROOT, avatar_file.name)
        # default_storage.save(save_path, avatar_file)
        #
        # formData.avatar = avatar_file.name
        formData.save()

        return redirect("/create-user/")

    else:
        return redirect('/dashboard/')

users/views/csv_import.py
from django.shortcuts import render, redirect, reverse
# from django.contrib.auth.decorators import login_required

import csv, io
from django.contrib import messages
from users.models import User


def user_csv_import(request):
    template = "CSV_import.html"
    prompt = {
        'order': 'Order of the csv file should be'
                 'Email, Name, Password, Phone, Avatar, Status, Designation, Is Active, Is Staff, Is Admin, Is Viewer'
    }
    if request.method == "GET":
        return render(request, template, prompt)

    csv_file = request.FILES['file']

    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'This is not a csv file')

    data_set = csv_file.read().decode('UTF-8')
    print(data_set)
    io_string = io.StringIO(data_set)
    next(io_string)
    for column in csv.reader(io_string, delimiter=',', quotechar="|"):

        _, created = User.objects.update_or_create(
            email=column[0],
            name=column[1],
            password=column[2],
            phone=column[3],
            avatar=column[4],
            status=column[5],
            designation=column[6],
            is_active=column[7],
            is_staff=column[8],
            is_admin=column[9],
            is_viewer=column[10]
        )
    context = {}
    return render(request, template, context)

users/views/dashboard.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required


@login_required(login_url='/login/')
def dashboard_view(request):
    """
    This view renders Dashboard
    """
    context ={
        "title": "Home"
    }
    return render(request, 'inventro_chart.html', context)

users/views/error_404.py
from django.shortcuts import render

def handler404(request):
    return render(request, '404.html', status=404)

users/views/error_500.py
from django.shortcuts import render

def handler500(request):
    return render(request, '500.html', status=500)

users/views/login.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_protect

@csrf_protect
def login_view(request):
    """
        This view renders Dashboard
        """
    if request.user.is_authenticated:
        #if User is already logged in redirects to Home Page
        return redirect("/dashboard/")

    if request.method == "POST":
        #if user is not logged in redirects to Login page
        username = request.POST.get("email")
        password = request.POST.get("password")
        remember = request.POST.get("remember")
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect("/dashboard/")
            else:
                return render(request, 'login.html')
        else:
            return render(request, 'login.html')
    else:
        return render(request, 'login.html')

users/views/logout.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


@login_required(login_url='/login/')
def logout_view(request):
    """
        This view logs out User
    """
    logout(request)
    return redirect('/')

users/views/user_detail.py
from django.shortcuts import render, redirect, get_object_or_404
from users.models.user_model import User
from django.contrib.auth.decorators import login_required



@login_required(login_url='/login/')
def user_detail_view(request, id):
    """
        This view renders User Detail page with a details of selected user
    """
    if request.user.is_admin:
        user_obj = get_object_or_404(User, id=id)
        context = {
            "user": user_obj,
            "title": "User Details"

        }
        return render(request, "user_detail.html", context)
    else:
        user_obj = get_object_or_404(User, id=request.user.id)
        context = {
            "user": user_obj,
            "title": "User Details"

        }
        return render(request, "user_detail.html", context)

users/views/user_list.py
from django.shortcuts import render,redirect
from users.models.user_model import User
from django.contrib.auth.decorators import login_required



@login_required(login_url='/login/')
def user_list_view(request):
    """
        This view renders All user page with a list of all registered user
    """
    if request.user.is_admin:
        queryset = User.objects.all()
        context = {
            "user_list": queryset,
            "title":"All Users"
        }
        return render(request, 'user_list.html', context)
    else:
        return redirect('/dashboard/')

users/templates/CSV_import.html
{% extends 'dashboard.html' %}
{% block content %}
    <div class="col-md-12">
        <div class="modal-content col-md-12">
            <div class="modal-header">
                <h4 class="modal-title text-center">CSV File Sample</h4>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <section class="content">
                        <form method="POST" action="{% url 'users:user_csv_import' %}" accept-charset="UTF-8"
                              enctype="multipart/form-data">
                            <div class="btn-right">
                                <button type="button"
                                        class="btn btn-info btn-flat btn-addon"><i
                                        class="fa fa-user"></i>Submit
                                </button>
                            </div>
                            <div class="background-csv text-center">
                                <img src="/static/images/csv_demo.jpg" style="width: 100%;height: 100%;" alt="Upload file format"/>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="row div-margin-custom-3">
                                            <label for="name">Upload your file in the format above<span class="text-danger">*</span></label>
                                        </div>
                                        <input type="file" id="real-file" class="hidden"/>
                                        <button type="button" id="custom-button" class="btn btn-choose btn-flat">Choose File
                                        </button>
                                        <span id="custom-text">No file chosen</span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </section>
                </div><!-- /# main -->
            </div>
        </div>
    </div>

    <script type="text/javascript">

        const realFileBtn = document.getElementById("real-file");
        const customBtn = document.getElementById("custom-button");
        const customTxt = document.getElementById("custom-text");
        customBtn.addEventListener("click", function () {
            realFileBtn.click();
        });
        realFileBtn.addEventListener("change", function () {
            if (realFileBtn.value) {
                customTxt.innerHTML = realFileBtn.value.match(
                    /[\/\\]([\w\d\s\.\-\(\)]+)$/
                )[1];
            } else {
                customTxt.innerHTML = "No file chosen";
            }
        });

    </script>
{% endblock %}

{% block script %}
    <script>

        $("#user-menu").addClass("active open");
        $("#upload-csv-file-menu").addClass("active");

    </script>
{% endblock %}

users/templates/Login.html
{% extends 'login_base.html' %}

{% block login %}

    <div class="login-form">

        <h4>Login</h4>
        <form action= "" method="POST" data-parsley-validate="">
            {% csrf_token %}
            <div class="row form-group">
                <label class="control-label">Email address</label>
                <div class="has-feedback">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="ti-user"></i></span>
                        {# Fring-added data-parsley-trigger="change" #}
                        <input type="email" class="form-control"  name="email" required="" data-parsley-trigger="change">
                    </div>
                    {#                    <span class="ti-check form-control-feedback"></span>#}
                    <span class="sr-only">(success)</span>
                </div>
            </div>
            <div class="row form-group">
                <label class="control-label">Password</label>
                <div class="has-feedback">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="ti-lock"></i></span>
                        {# Fring- added data-parsley-minlength="6" #}
                        <input type="password" class="form-control" required name="password" data-parsley-minlength="5">
                    </div>
                    {#                    <span class="ti-check form-control-feedback"></span>#}
                    <span class="sr-only">(success)</span>
                </div>
                <div class="checkbox">
                        {# Fring- added css class forget-message-position#}
                    <label class="pull-right forget-message-position">
                        <a href={{ '/password-reset/' }}>Forgotten Password?</a>
                    </label>
                </div>
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="remember" value="True"> Remember Me
                </label>
            </div>
            <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30">Sign in</button>
        </form>
    </div>

{% endblock login %}

users/templates/create_user.html
{% extends 'dashboard.html' %}
{% block content %}
    {#   PUT YPUR CODE BELOW    #}
    <div class="modal-content col-md-12">
        <div class="modal-header">
            <h4 class="modal-title text-center">Create User</h4>
        </div>
        <div class="modal-body">
            {#Create User Form#}
            <form class="m-b-30" _lpchecked="1" action="{% url 'users:store_user' %}" method="POST"
                  accept-charset="UTF-8" enctype="multipart/form-data"
                  data-parsley-validate="">{# Rafeen #} {# Fring- added data-parsley-validate="" #}
                {% csrf_token %}
                <div class="btn-right">
                    <button type="submit" class="btn btn-info btn-flat btn-addon">
                        <i class="fa fa-user"></i>Create User
                    </button>
                </div>
                <div class="tab-content">
                    <div id="home" class="panel panel-success m-t-15 tab-pane fade active in">
                        <div class="panel-body">
                            {# User Name Field #}
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="name">Name <span class="text-danger">*</span></label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                        <input class="form-control" name="name" type="text" id="name" required="">
                                    </div>
                                </div>
                            </div>
                            {# User Email Field #}
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="email">Email Address<span
                                            class="text-danger">*</span> </label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                                        <input class="form-control" name="email" type="email" id="email" required=""
                                               data-parsley-trigger="change">
                                        {# Fring- added data-parsley-trigger="change" type="email"#}
                                    </div>
                                </div>
                            </div>
                            {# User Password Field #}
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="password">Password <span class="text-danger">*</span>
                                    </label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                        <input class="form-control" name="password" type="password" value=""
                                               id="password" required="" data-parsley-minlength="6">
                                        {# Fring- added data-parsley-minlength="6" #}
                                    </div>
                                </div>
                            </div>
                            {# User Phone Number Field #}
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Phone Number<span
                                            class="text-danger">*</span>
                                    </label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-phone"
                                                                           aria-hidden="true"></i></span>
                                        <input class="form-control" name="phone" value="" id="Phone" required=""
                                               data-parsley-type="number"> {# Fring- added data-parsley-type="number" #}
                                    </div>
                                </div>
                            </div>
                            {# User Designation Field #}
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="role_id">Designation<span class="text-danger">*</span>
                                    </label>
                                    <div class="input-group"><span class="input-group-addon"><i
                                            class="fa fa-id-card"></i></span>
                                        <select class="form-control select2-hidden-accessible" id="designation"
                                                name="designation" tabindex="-1" aria-hidden="true">
                                            <option value="Manager">Manager</option>
                                            <option value="Seller">Seller</option>
                                            <option value="Shop keeper">Shopkeeper</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            {# User Role Field #}
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="role_id">User Role <span class="text-danger">*</span>
                                    </label>
                                    <div class="input-group"><span class="input-group-addon"><i class="fa fa-user"></i></span>
                                        <select class="form-control select2-hidden-accessible" id="role_id"
                                                name="role_id" tabindex="-1" aria-hidden="true">
                                            <option value="s">Staff</option>
                                            <option value="a">Admin</option>
                                            <option value="v">Viewer</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            {# User Status Field #}
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="role_id">User Status <span class="text-danger">*</span>
                                    </label>
                                    <div class="input-group"><span class="input-group-addon"><i
                                            class="fa fa-align-left"></i></span>
                                        <select class="form-control select2-hidden-accessible" id="user_status"
                                                name="user_status" tabindex="-1" aria-hidden="true">
                                            <option value="Active">Active</option>
                                            <option value="Deactive">Deactive</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            {# User Pic succeed #}
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="row div-margin-custom-3">
                                        <label for="name">Upload Picture<span class="text-danger">*</span></label>
                                    </div>
                                    <input type="file" id="real-file" class="hidden"/>
                                    <button type="button" id="custom-button" class="btn btn-choose btn-flat">Choose
                                        File
                                    </button>
                                    <span id="custom-text">No file chosen</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript">
        const realFileBtn = document.getElementById("real-file");
        const customBtn = document.getElementById("custom-button");
        const customTxt = document.getElementById("custom-text");
        customBtn.addEventListener("click", function () {
            realFileBtn.click();
        });
        realFileBtn.addEventListener("change", function () {
            if (realFileBtn.value) {
                customTxt.innerHTML = realFileBtn.value.match(
                    /[\/\\]([\w\d\s\.\-\(\)]+)$/
                )[1];
            } else {
                customTxt.innerHTML = "No file chosen, yet.";
            }
        });

    </script>

{% endblock %}
{% block script %}
    <script>

        $("#user-menu").addClass("active open");
        $("#create-user-menu").addClass("active");

    </script>
{% endblock %}